### ISSUE TITLE
Support co-exist with other Kubernetes schedulers

### ISSUE THREAD

**Issue by yangwwei** [apache/incubator-yunikorn-core#21]
Kubernetes supports to have multiple schedulers in one cluster. Actually, the simplest way to deploy YuniKorn is to co-exist with the default scheduler. Deployment mode has the following 3 options 

1. Disable default scheduler and just run YuniKorn.
2. Run both default scheduler and YuniKorn, but each manages a dedicated set of nodes.
3. Run both default scheduler and Yunikorn, and they share cluster nodes.

there is no additional work to support opt1; to support opt2, we only need some small effort, for example, we can leverage taints and tolerations to isolate some nodes for YuniKorn; for opt3, there is much more work to do, e.g how to handle shared resources.

**Comment by wilfred-s** [comment]
moved to jira:
https://issues.apache.org/jira/browse/YUNIKORN-16
