### ISSUE TITLE
Introduce a health check in YuniKorn

### ISSUE THREAD

**Issue by sunilgovind** [apache/incubator-yunikorn-core#23]
During deployment of yunikorn, trying to achieve a health probe done something similar to below.

`livenessProbe:
 httpGet:
    path: /healthz
    port: 10251
       initialDelaySeconds: 15
       timeoutSeconds: 1`

**Comment by yangwwei** [comment]
Hi @sunilgovind 

We have some states in shim, but in yunikorn-core we are trying to get it less depending on the state. This means we can easily obtain health status from shim but not core, because we are exposing our reset api from the core. How do you plan to get this done?

**Comment by wilfred-s** [comment]
moved to jira:
https://issues.apache.org/jira/browse/YUNIKORN-17
