### ISSUE TITLE
Add rest API to retrieve app/container history info

### ISSUE THREAD

**Issue by yangwwei** [apache/incubator-yunikorn-core#36]
this is required by https://github.com/cloudera/yunikorn-web/issues/12

**Comment by yangwwei** [comment]
Hi @sunilgovind 

https://github.com/cloudera/yunikorn-web/issues/12 is blocked by this one, do you have an estimation when this can be done?

**Comment by wilfred-s** [comment]
moved the issue to jira:
https://issues.apache.org/jira/browse/YUNIKORN-14
