### ISSUE TITLE
Revisit node sorting algorithm for fairness

### ISSUE THREAD

**Issue by wangdatan** [apache/incubator-yunikorn-core#76]
Currently, we're using DominantRatio for the node sorting algorithm

```
func CompUsageShares(left, right *Resource) int {
    lshares := getShares(left,nil)
    rshares := getShares(right,nil)

    return compareShares(lshares, rshares)
}
```
Which is not good, two reasons: 

1) Dominate resource compare is about 8X more expensive than single float compares for two resource types. 

2) Dominate resource is not stable when we have scarce resource types like GPU. A node with 192GB mem, 32 vcores, and 1 GPU available, compared to 168GB mem, 64 vcore and 8 GPU available; the prior one can go first because of the following logic: 

```
       if total == nil || total.Resources[k] == 0 {
            // negative share is logged
            if v < 0 {
                log.Logger().Debug("usage is negative no total, share is also negative",
                    zap.Int64("resource quantity", int64(v)))
            }
            shares[idx] = float64(v)
            idx++
            continue
        }
```

I think we should discard dominate resource compare for node resource. Instead, we just use one resource type (like vcores) to compare available resource.

**Comment by wangdatan** [comment]
cc: @wilfred-s , @yangwwei , @sunilgovind , @TaoYang526

**Comment by TaoYang526** [comment]
Thanks @wangdatan for raising this issue. I have considered about this and would like to share my thoughts.
I have tested the performance and found the most time-consuming part is to iterate map items, time cost of iterating a map is about 20 times the time cost of iterating a slice in my local test. Take one resource ("memory" or "vcore") into account seems a temporary solution but a final solution.  
For node sorting algorithm, current method is not good enough to meet our requirements like scarce resource and node affinity, can we support priorities algorithm of k8s just as predicates did? In that way, we can sorting nodes according to customized plugins and make it more flexible to meet requirements of different users.
For the structure of resources, can we take "memory" and "vcore" as separate resources or keep them in a slice and leave other resources in the map?  I have discussed with @yangwwei and we thought it's not urgent to do and we can improve it later.

**Comment by wangdatan** [comment]
@TaoYang526 

> I have tested the performance and found the most time-consuming part is to iterate map items, time cost of iterating a map is about 20 times the time cost of iterating a slice in my local test. Take one resource ("memory" or "vcore") into account seems a temporary solution but a final solution.
> For node sorting algorithm, current method is not good enough to meet our requirements like scarce resource and node affinity, can we support priorities algorithm of k8s just as predicates did? In that way, we can sorting nodes according to customized plugins and make it more flexible to meet requirements of different users.

I think we should avoid global sorting during scheduling. It should be a sorted node list(s) defined in policies. The existing behavior of node sorting and scheduling looks like: 

```
nodeList = copy-node-list 

spin-off 16 threads to do: 
   sort(nodeList);
   schedule(req, nodeList)
```
This doesn't look correct since multiple gorountines sorting on the same slice could lead to problems.

> For the structure of resources, can we take "memory" and "vcore" as separate resources or keep them in a slice and leave other resources in the map? I have discussed with @yangwwei and we thought it's not urgent to do and we can improve it later.

If we do that, we have to carry the complexities to maintain separate stored mem/vcores for all resource-related operations.

The long term solution is to avoid sorting node completely during allocation, all sorting should be done asynchronously in a separate thread(s).

**Comment by TaoYang526** [comment]
@wangdatan 
I would like to clarify that to support priorities algorithm is not completely copy the implementation but reuse the multi-scorer mechanism to enhance the flexibility, we can do sorting asynchronously if sorting list can be updated in time, such as keep scores in cache and just update the sorting list incrementally.
>If we do that, we have to carry the complexities to maintain separate stored mem/vcores for all resource-related operations.
I have took a look at changes about this, perhaps we just need to update the fundamental operations about resource in resources.go and some test cases. But it's fine to keep this way on if it won't be a bottleneck for performance.

**Comment by yangwwei** [comment]
I agree this is indeed a problem, which we should fix and make sure we have UT coverage.
This is an interesting problem, in K8s we can customize sorting results by applying different priorities, like https://kubernetes.io/docs/concepts/scheduling/kube-scheduler/#scoring. These are configurations for the default scheduler. For yunikorn, it will be hard to support all of these. I think what we can do is to make this configurable + pluggable, but not using the same semantics like K8s.

**Comment by TaoYang526** [comment]
>  I think what we can do is to make this configurable + pluggable, but not using the same semantics like K8s.
Agree with that, in this way we can extend more scoring policies to consider node utilization, scarce resource and so on.

**Comment by wilfred-s** [comment]
moved to jira:
https://issues.apache.org/jira/browse/YUNIKORN-21
